### PR TITLE
Error if rose-suite-cylc-install.conf exists and not a re-install

### PR DESCRIPTION
**Pull request by wxtim**
These changes partially address https://github.com/cylc/cylc-flow/issues/4888

## Requirements check-list

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to `setup.cfg`.
- [x] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Review by hjoliver — APPROVED** [review]

**Comment by hjoliver** [comment]
Good question. I guess there's no other way of getting there, other than via `cylc install`?

**Comment by wxtim** [comment]
> Good question. I guess there's no other way of getting there, other than via `cylc install`?

Is there anything to stop a user manually creating this file?

**Comment by MetRonnie** [comment]
What if the user deliberately left the file there to get cylc-rose to pick up the options?

**Comment by wxtim** [comment]
> What if the user deliberately left the file there to get cylc-rose to pick up the options?

Shouldn't be doing that - it's a reserved filename.  (I should double check that we throw an exception if they add it manually to cylc-src!?)

The legit case is where one is using `cylc re-install` and there's a swathe of logic for that.

**Comment by MetRonnie** [comment]
Ah but hang on a minute, if the run dir already exists then `cylc install` itself will fail with
```
WorkflowFilesError: '~/cylc-run/tmpflow' already exists
To reinstall, use `cylc reinstall`
```

**Comment by wxtim** [comment]
> Ah but hang on a minute, if the run dir already exists then `cylc install` itself will fail with
> 
> ```
> WorkflowFilesError: '~/cylc-run/tmpflow' already exists
> To reinstall, use `cylc reinstall`
> ```
> 
> Unless I am missing something?

No, I don't think you are - I'm trying to work out if we should keep this because it covers an eventuality like the one Hilary came across, or just ditch it because it should never happen.

**Comment by wxtim** [comment]
Closed on the basis that the circumstance which cause the issue to arise amount to a bug in Cylc and therefore should not be handled.

**Pull request closed without merging**
