### PR TITLE
Log warning [jinja2/empy:suite.rc] is deprecated

### PR DESCRIPTION
**Pull request by datamel**
These changes close https://github.com/cylc/cylc-rose/issues/123

## Requirements check-list

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to `setup.cfg`.
- [x] Appropriate tests are included (unit and/or functional).
- [x] No change log entry required (why? e.g. only a warning).
- [x] No documentation update required.

### CODE REVIEW

**Review by wxtim — CHANGES_REQUESTED** [review]
I've just tried this and I have a couple of things which I don't think are quite right:

#### Define section once, get warning twice 

```bash
> cat rose-suite.conf 
[jinja2:suite.rc]
> cylc install 
INSTALLED temp1/run10 from /net/home/h02/tpilling/cylc-src/temp1
2022-04-08T08:30:09+01:00 WARNING - [jinja2:suite.rc] is deprecated. Use [template variables] instead.
2022-04-08T08:30:09+01:00 WARNING - [jinja2:suite.rc] is deprecated. Use [template variables] instead.
```

#### It only works for Cylc install:

Same workflow and rose-suite.conf:

```bash
> cylc validate .
Valid for cylc-8.0rc3.dev
```

I think that you need to run the check in a function called by `cylc.rose.entry_points.pre_configure` such as `cylc.rose.entry_points.get_rose_vars` - around line 125 there is a check for a deprecated root_dir setting - I think here would be a reasonable place to put it - You might even create a new method `cylc.rose.utils.deprecation_warnings()` and move the existing warning into it...

**Review by wxtim — APPROVED** [review]
Thank you @datamel 
Merge if you wish - neither of my comments should block that!

**Comment by datamel** [comment]
Feedback addressed. Thanks @wxtim.

**Comment by datamel** [comment]
Feedback addressed. Thanks @wxtim.

**Pull request merged**
