### PR TITLE
Revert "Revert "Create cylc config save file.create log rose conf""

### LINKED ISSUE #10: post_install: dump the parsed configuration to conf/<timestamp>-rose-suite.conf
https://cylc.github.io/cylc-admin/proposal-rose-suite-run.html#log-file-changes

### PR DESCRIPTION
**Pull request by wxtim**
Replaces #29 😢 
Closes #10

### CODE REVIEW

**Comment by MetRonnie** [comment]
Huh? I'm confused now!

**Comment by wxtim** [comment]
> Huh? I'm confused now!

Unsurprising. I accidentally merged #29 .
I created a revert PR, and merged it.
I couldn't work out how to re-open the original PR.
I asked to revert the reversion.
Which is this PR.

**Review by MetRonnie — APPROVED** [review]
Index is identical to bde2c560e1ef843bdbf56df651141a95b8be3d28 (could just hard-reset and force-push if acceptable)

**Comment by wxtim** [comment]
> Index is identical to bde2c56 (could just hard-reset and force-push if acceptable)

I'd say it's acceptable. But having £"$%^& up once today I'm not in the mood for Git Danger.

**Review by oliver-sanders — APPROVED** [review]

**Pull request merged**
