### PR TITLE
1.3.0

### PR DESCRIPTION
**Pull request by oliver-sanders**
* Pushed upstream/master:2.2.x
* Bumped the version on this PR
* cylc-admin thinggy: https://github.com/cylc/cylc-admin/pull/169

### CODE REVIEW

**Review by MetRonnie — APPROVED** [review]

**Comment by MetRonnie** [comment]
I'm having a look at the test failures

**Comment by MetRonnie** [comment]
I don't get this one
```
ERROR tests/functional/test_reinstall.py::test_cylc_reinstall_run - optparse.OptionConflictError:
  option --clear-rose-install-options: conflicting option string(s): --clear-rose-install-options
```
May need @wxtim to have a look

**Comment by oliver-sanders** [comment]
Oh, nasty.

**Comment by wxtim** [comment]
Simple breakage -
```bash
sed -i 's@workflow_files import reinstall_workflow@install import reinstall_workflow@' tests/functional/test_reinstall
```

**Comment by wxtim** [comment]
> Next issue is this one:
> 
> ```
> optparse.OptionConflictError: option --clear-rose-install-options: conflicting option string(s): --clear-rose-install-options
> ```

Unrelated to Cylc Rose - fix up

**Comment by oliver-sanders** [comment]
Re-running the tests, they should pass now...

**Review by MetRonnie — APPROVED** [review]

**Pull request merged**
