### PR TITLE
fix mailmap

### PR DESCRIPTION
**Pull request by wxtim**
Update mailmap to avoid WXTIM appearing.

### CODE REVIEW

**Comment by MetRonnie** [comment]
D'oh, also need to include `.github/workflows/shortlog.yml` itself

**Comment by MetRonnie** [comment]
😑 https://www.githubstatus.com/incidents/y5hdmv0p49x3

**Comment by hjoliver** [comment]
@wxtim I pushed a commit to this branch, to add my own name to the contributor list and .mailmap.

**Comment by hjoliver** [comment]
And another commit. Turns out many of us were not using `.mailmap` correctly.

Before my two commits:
```
└o git shortlog -se
     2  Bruno P. Kinoshita <kinow@users.noreply.github.com>
     2  Hilary James Oliver <hilary.j.oliver@gmail.com>
     3  Mel Hall <37735232+datamel@users.noreply.github.com>
    46  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
    26  Ronnie Dutta <61982285+MetRonnie@users.noreply.github.com>
   172  Tim Pillinger <26465611+wxtim@users.noreply.github.com>
     6  github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
```


And after:
```
└o git shortlog -se
     2  Bruno Kinoshita <kinow@apache.org>
     4  Hilary Oliver <hilary.j.oliver@gmail.com>
     3  Mel Hall <mel.hall@metoffice.gov.uk>
    46  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
    26  Ronnie Dutta <ronnie.dutta@metoffice.gov.uk>
   172  Tim Pillinger <tim.pillinger@metoffice.gov.uk>
     6  github-actions[bot] <github-actions@no-reply.github.com>
```

**Comment by MetRonnie** [comment]
> And another commit. Turns out many of us were not using `.mailmap` correctly.

I don't think that mattered? https://git-scm.com/docs/gitmailmap#_syntax

**Review by datamel — COMMENTED** [review]
Just thinking for consistency across repos, if adding contributors names, maybe put them in brackets with the explanatory comments as in: https://github.com/cylc/cylc-doc/pull/444

**Comment by hjoliver** [comment]
>  I don't think that mattered? 

Well, it depends what you mean by "mattered" exactly.  The simple format is fine so long as your commit email address is valid, for all your commits.  Otherwise list address as well as name results in a shortlog mess.

On current cylc-flow master, for instance:
```console
$ git shortlog -se | grep Hilary
  6124  Hilary Oliver <h.oliver@niwa.co.nz>
  2970  Hilary Oliver <hilary.j.oliver@gmail.com>
     4  Hilary Oliver <hilary.oliver@niwa.co.nz>
     3  Hilary Oliver <hilary@Megan-Olivers-MacBook-Pro.local>
     2  Hilary Oliver <hilary@localhost.localdomain>
     1  Hilary Oliver <holiver@eld084.desktop.frd.metoffice.com>
```
Whereas on my .mailmap fix branch:
```console
$ git shortlog -se | grep Hilary
  9101  Hilary Oliver <hilary.j.oliver@gmail.com>
```

**Comment by MetRonnie** [comment]
I meant I don't think it matters if someone's "proper" email address is in mailmap as long as git thinks there is only 1 of that person

**Review by MetRonnie — APPROVED** [review]

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
