### PR TITLE
Exit immediately if no rose suite.conf

### PR DESCRIPTION
**Pull request by wxtim**
Make pre-configure act like post install.

Because pre-configure uses Cylc global config in the process of getting `ROSE_ORIG_HOST` it creates an instance of the global config object with the default items if it is called before the global config is otherwise instantiated, such as when loading and parsing a global config file.

**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] ~Tests are included~ Change in code covered by existing tests.
- [x] ~`CHANGES.md` entry included if this is a change that can affect users~ Don't want to advertise that this _was_ possible before.
- [x] ~[Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.~
- [x] ~If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.~

### CODE REVIEW

**Review by oliver-sanders — APPROVED** [review]

**Comment by MetRonnie** [comment]
Tests are in a bit of a mess at the moment. Disregarding the 3.7 job failing on installation, there are 8 tests failing on the 3.8 job (but 5 of those are failing on master)

**Comment by oliver-sanders** [comment]
(taking a look at the rose-stem flakeyness)

**Comment by oliver-sanders** [comment]
This should stabilise the rose-stem tests: https://github.com/cylc/cylc-rose/pull/268

**Comment by oliver-sanders** [comment]
The reinstall tests are broken because the interface has changed from sync to async.

**Review by MetRonnie — APPROVED** [review]
LGTM, are we happy to merge?

**Comment by oliver-sanders** [comment]
Will run tests locally...

**Comment by oliver-sanders** [comment]
I get the same fails on master as on this branch.

**Pull request merged**
